import "@/styles/globals.css";
import localFont from "next/font/local";
import { type Metadata } from "next";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const triakisFont = localFont({
  src: "../../public/fonts/Triakis-Font-VF.ttf",
  display: "swap",
});

export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  return (
    <html lang="en" className={triakisFont.className}>
      <body className="flex min-h-screen flex-col bg-black transition duration-300 ease-in-out">
        <Providers>
          {children}
          {modal}
        </Providers>
        <div id="modal-root" />
      </body>
    </html>
  );
}
