import "@/styles/globals.css";
import localFont from "next/font/local";
import { type Metadata } from "next";
import Providers from "./providers";
import { CustomToaster } from "@/components/Toasters/CustomToaster";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const triakisFont = localFont({
  src: "../../public/fonts/Triakis-Font-VF.ttf",
  display: "swap",
});

export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  return (
    <html lang="en" className={triakisFont.className}>
      <body className="relative flex min-h-screen flex-col border border-blue-900/60 bg-[#04070F] transition duration-300 ease-in-out">
        <Providers>
          {children}
          {modal}
        </Providers>
        <div id="modal-root" />
        <CustomToaster />
        <div className="fixed bottom-0 left-0 right-0 -z-10 aspect-square h-[25vh] w-full border bg-[#3ECFDE]/20 opacity-30 blur-[300px]" />
      </body>
    </html>
  );
}
